# Simulador de Lanzamiento de Dados

In [1]:
import random as rd
import matplotlib.pyplot as plt
import numpy as np

import sys
sys.path.append("../src")

from simulador import Simulador


In [2]:
caras_dado=6
nLanzamientos=1000000
nDados=2

In [3]:
Simulador.dados(caras_dado,nDados)
lanzamintos=Simulador.lanzamientos(nLanzamientos)
print(lanzamintos)

[[6 6]
 [4 5]
 [4 6]
 ...
 [1 1]
 [1 2]
 [2 3]]


In [ ]:
# hallar las frecuencias de los dados prototipo

primer_dado, frecuencias_primer_dado= np.unique(lanzamintos[:, 0], return_counts=True)
segundo_dado, frecuencias_segundo_dado= np.unique(lanzamintos[:, 1], return_counts=True)

print(primer_dado)
print(frecuencias_primer_dado)


[1 2 3 4 5 6]
[167005 166927 167181 165565 167143 166179]


**Nota**: ya se tiene el prototipo ahora falta guardarlo en un dicionario y depues pasarlo en un bucle y de ultimo a una funcion